### ISSUE TITLE
Where can I find the data pointing to pd.read_csv()?

### ISSUE THREAD

**Issue by slava-keshkov** [carlomazzaferro/scikit-hts-examples#3]
Hi there!

I would like to test the notebook you are so kind to share in /M5. 

However, there is no csv file that you mention here:

```
train = pandas.read_csv(os.path.join(data, 'sales_train_validation.csv'), 
                        encoding='utf-8', 
                        engine='c')# .drop('item_id', 1)

```

Let me know where I can find it

**Comment by carlomazzaferro** [comment]
https://www.kaggle.com/c/m5-forecasting-accuracy/data here!
