### ISSUE TITLE
What are the options accepted by model param?

### ISSUE THREAD

**Issue by slava-keshkov** [carlomazzaferro/scikit-hts-examples#4]
Hi there!

For this line of code:

`clf = HTSRegressor(model= 'prophet', revision_method='OLS', n_jobs=1, low_memory = True)
`
What are some of the other string values for the `model` variable accepted by HTSRegressor?

I was looking for them here, but could not find a list of exact strings: https://scikit-hts.readthedocs.io/en/latest/modules.html

Thanks in advance!

**Comment by carlomazzaferro** [comment]
Model params are params that get sent to the underlying model, i.e. prophet in this case. Refer to the https://facebook.github.io/prophet/docs/quick_start.html#python-api for the possible parameters that you can pass to the model, to the fit function, and to the predict function

**Comment by slava-keshkov** [comment]
I meant to say we can pass `model = "prophet"`, what else can we pass to model = "?" 
I see in the documentation that you have Auto Arima, Sarimax and ETS, but what are the notations for each of them?

<img width="697" alt="Screenshot 2020-10-28 at 17 42 50" src="https://user-images.githubusercontent.com/72742546/97451741-16bf3680-1945-11eb-8957-fce61122a3f3.png">
The documentation does not contain a list like ['prophet', 'auto-arima' or 'auto_arima', 'ets' or 'ETS']

<img width="682" alt="Screenshot 2020-10-28 at 17 42 56" src="https://user-images.githubusercontent.com/72742546/97451750-19ba2700-1945-11eb-8519-29a660e4577f.png">

**Comment by carlomazzaferro** [comment]
I see. Good call, that should indeed be documented, and the possible options can be found here: https://github.com/carlomazzaferro/scikit-hts/blob/master/hts/_t.py#L27

If you'd like to contribute, a PR would be very much welcomed.
